#

application:
  namespace: smarter
  appName: smarter-audio-client

image:
  #repository: imtest
  repository: ghcr.io/smarter-project/audio-client
  # @default -- chart.appVersion
  tag: ""
  pullPolicy: IfNotPresent

configuration:
  pulsesource: alsa_input.hw_1_0
  loglevel: INFO
  pollfrequency: 20
  mqtt:
    host: smarter-fluent-bit
  smarter_inference:
    host: smarter-inference
    port: 2520
  pulseaudio:
    host: smarter-pulseaudio
    port: 4713
